### ISSUE TITLE
Mkdocs configuration -- Setting syntax highlighting breaks source code collapse in auto-generated reference docs

### ISSUE THREAD

**Issue by ncilfone** [timothycrosley/portray#82]
```toml
[tool.portray.mkdocs]
repo_url = "https://github.com/fidelity/spock"
markdown_extensions = ["pymdownx.superfences", "pymdownx.highlight"]
```

See here for an example:

https://fidelity.github.io/spock/reference/spock/addons/s3/utils/
